# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Python code
        run: pylint /C:/Users/lisal/voting-app*.py

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run security checks
        run: bandit -r /C:/Users/lisal/voting-app

  build:
    runs-on: ubuntu-latest

    needs: [lint, security]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: packer build -var 'ansible_playbook=deploy.yml' packer.json

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push valentinleroy/voting-app:latest
